### ISSUE TITLE
用keras_bert加载有点问题

### ISSUE THREAD

**Issue by bojone** [ArthurRizar/tensorflow_ernie#1]
你好，我试图用keras_bert的load_trained_model_from_checkpoint加载你转的ernie权重，出现：

> tensorflow.python.framework.errors_impl.NotFoundError: Key bert/encoder/layer_0/output/dense/bias not found in checkpoint

加载官方提供的chinese_L-12_H-768_A-12权重是正常的。

不知道有什么解决方法或者建议吗？

keras_bert：https://github.com/CyberZHG/keras-bert

**Comment by ArthurRizar** [comment]
感谢指正，当时名字写成了bert/encoder/layer_0/output/dense/beta，所以找不到，这两天我修复一下

**Comment by bojone** [comment]
哦哦，感谢。
十分期待～

**Comment by ArthurRizar** [comment]
> 哦哦，感谢。
> 十分期待～

已经更新了

**Comment by bojone** [comment]
你好，最新版已经下载了，可以加载。但有点问题。

我之前用官方发布的权重（chinese_L-12_H-768_A-12）+keras_bert来fine tune过一个模型，训练情况如下：
epoch 1, loss=1.3811, acc=0.8606
epoch 2, loss=0.3390, acc=0.8742
epoch 3, loss=0.1884, acc=0.8668
...

直接将权重换成你提供的ernie之后，训练过程如下：
epoch 1, loss=4.7382, acc=0.5260
epoch 2, loss=0.8871, acc=0.8203
epoch 3, loss=0.5515, acc=0.8321
...

这差异似乎太大了，难道权重没有加载对吗？请问大佬有没有做过输出比对呢？我没有跑过paddle版本的。

另外，官方提供的bert权重，加载后的总参数量是101,678,592；而ernie加载后的总参数量是99,277,056

**Comment by ArthurRizar** [comment]
哈哈，不是大佬。不过我之前做过文本分类的对比，这两个模型差异不大，有些场景ernie更高一点，大概0.5%，有些bert更高一点，也是0.5%。官方bert可能有其他输入和输出的参数，ernie只保存了embedding层，multi head attention层，pooled层的参数，少了以cls开头的与pretrain有关的参数

**Comment by ArthurRizar** [comment]
对了，ernie与bert的还有超参数的区别，1.bert用gelu，ernie用relu
2.bert的position embedding的维度是512，而ernie是513

使用ernie需要完全覆盖那几个配置文件，包括vocab和bert_config.json

**Comment by bojone** [comment]
感谢提醒，换成relu后确实能够逼近原来bert的效果了，只是低了0.7%

还有一个疑惑，据说ernie与bert还有一些超参数是不同的，比如layernorm的epsilon，直觉上这些参数不会影响效果，但事实上模型深了之后，微小的差异累积起来，谁也不好说。你觉得呢？

**Comment by CyberZHG** [comment]
@bojone Layer norm在bert原版本中是没有epsilon的，加上eps 12层后影响也不是很大，几乎可以忽略
