### ISSUE TITLE
请问可以开源一下转化为tensorflow模型的脚本吗？

### ISSUE THREAD

**Issue by RyanHuangNLP** [ArthurRizar/tensorflow_ernie#2]
可以开源将paddlepaddle转为tensorflow的脚本吗

**Comment by ArthurRizar** [comment]
> 可以开源将paddlepaddle转为tensorflow的脚本吗

这两天我整理下

**Comment by RyanHuangNLP** [comment]
十分感谢，期待期待

**Comment by cmiforsaken** [comment]
大佬的转换脚本已经开源了嘛？

**Comment by cmiforsaken** [comment]
期待大佬的脚本代码呀😂

**Comment by RyanHuangNLP** [comment]
@cmiforsaken 按照ernie里面的tensorflow的bert转换为paddle的代码，反过来写就好了

**Comment by ArthurRizar** [comment]
十分抱歉，前阵子比较忙，忘记了这件事，现在已经上传了转换代码
