### ISSUE TITLE
运行pad_to_np.py脚本出错

### ISSUE THREAD

**Issue by qiuhuiGithub** [ArthurRizar/tensorflow_ernie#7]
使用最新的ernie版本，运行出错,错误如下：
Traceback (most recent call last):
  File "pad_to_np.py", line 54, in <module>
    ernie_config=ernie_config)
  File "/home/xx/ERNIE/finetune/classifier.py", line 69, in create_model
    qids) = fluid.layers.read_file(pyreader)
UnboundLocalError: local variable 'pyreader' referenced before assignment
是ernie的问题吗？

**Comment by zhengyima** [comment]
同问

**Comment by zhengyima** [comment]
@ArthurRizar

**Comment by ArthurRizar** [comment]
我刚刚看了下新版的ernie代码，create_model他们做了修改，调用时需要加上is_classify=True才能定义pyreader这个对象，我修改一下
